apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testopspoc
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: testopspoc
    networking.gke.io/v1beta1.FrontendConfig: testopspoc
    networking.gke.io/managed-certificates: testopspoc
spec:
  defaultBackend:
    service:
      name: testopspoc
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testopspoc
spec:
  type: NodePort
  selector:
    app: testopspoc
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testopspoc
  labels:
    app: testopspoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testopspoc
  template:
    metadata:
      labels:
        app: testopspoc
    spec:
      containers:
        - name: testopspoc
          image: quiirex/nowted-app:latest
