name: Performance Testing

on: [push, pull_request]

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install k6
        run: sudo apt-get install -y k6

      - name: Run performance tests
        run: k6 run path/to/your/performance-tests.js
