name: Deployment

on:
  workflow_run:
    workflows:
      [
        'Lint',
        'Test Automation',
        'Test Management',
        'Performance Testing',
        'Security Testing',
      ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v1

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-image-name
