name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

  e2e-testing:
    name: E2E Testing
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run --e2e

  security-testing:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: e2e-testing
    services:
      app:
        image: quiirex/nowted-app:latest
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://app:3000'

  reporting:
    name: Reporting
    runs-on: ubuntu-latest
    needs: [linting, e2e-testing, security-testing]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Cypress testing report
        run: npx mochawesome-merge "cypress/reports/*.json" > report.json && npx marge report.json --reportFilename "testing_report" --reportTitle "Cypress Report" --reportPageTitle "Cypress Report"

      - name: Upload Cypress test reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: mochawesome-report

      - name: Upload k6 performance reports
        uses: actions/upload-artifact@v3
        with:
          name: k6-reports
          path: k6-reports

  # test-management:
  #   name: Test Management
  #   runs-on: ubuntu-latest
  #   needs: reporting
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Upload test results to Test Management Tool
  #       run: |
  #         curl -X POST -H "Content-Type: application/json" -d @path/to/consolidated-report.json http://test-management-tool/api/upload

  # deployment:
  #   name: Deployment
  #   runs-on: ubuntu-latest
  #   needs: test-management
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy to production
  #       run: pnpm run deploy

  # performance-testing:
  #   name: Performance Testing
  #   runs-on: ubuntu-latest
  #   needs: test-automation
  #   services:
  #     app:
  #       image: quiirex/nowted-app:latest
  #       ports:
  #         - 3000:3000
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install pnpm
  #       run: npm install -g pnpm

  #     - name: Install dependencies
  #       run: pnpm install

  #     - name: Build application
  #       run: pnpm run build

  #     - name: Wait for server to start
  #       run: npx wait-on http://app:3000

  #     - name: Run k6 local test
  #       uses: grafana/k6-action@v0.3.1
  #       with:
  #         filename: __tests__/performance/test.js
  #         flags: --vus 50 --duration 10s
