name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  e2e-testing:
    name: E2E Testing
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000

      - name: Run tests
        run: npx cypress run --e2e

      - name: Generate testing report
        run: npx mochawesome-merge "cypress/reports/*.json" > report.json && npx marge report.json --reportFilename "testing_report" --reportTitle "Cypress Report" --reportPageTitle "Cypress Report"

      - name: Upload testing report
        uses: actions/upload-artifact@v3
        with:
          name: testing_report
          path: mochawesome-report

  security-testing:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: e2e-testing
    services:
      app:
        image: quiirex/nowted-app:latest
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://app:3000'

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v3
        with:
          name: security-testing-reports
          path: security-testing-reports

  performance-testing:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: security-testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run k6 tests
        run: npm run test:performance

      - name: Upload k6 performance reports
        uses: actions/upload-artifact@v3
        with:
          name: performance-testing-reports
          path: performance-testing-reports
